
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int CONST = 5;
  public static final int UMINUS = 36;
  public static final int GREAT = 31;
  public static final int ELSIF = 16;
  public static final int COLONEQ = 27;
  public static final int NOTEQUAL = 28;
  public static final int SEMI = 20;
  public static final int LEFTMIDPAR = 18;
  public static final int INT = 45;
  public static final int ARRAY = 10;
  public static final int MINUS = 35;
  public static final int LESS = 29;
  public static final int WRITE = 48;
  public static final int NOT = 42;
  public static final int AND = 41;
  public static final int RECORD = 9;
  public static final int TYPE = 6;
  public static final int OR = 37;
  public static final int BOOL = 46;
  public static final int COMMA = 26;
  public static final int DIV = 39;
  public static final int BEGIN = 3;
  public static final int RIGHTMIDPAR = 19;
  public static final int GEQ = 32;
  public static final int WRITELN = 49;
  public static final int IF = 14;
  public static final int DOT = 21;
  public static final int UADD = 34;
  public static final int OF = 11;
  public static final int EOF = 0;
  public static final int EQUAL = 22;
  public static final int error = 1;
  public static final int MUL = 38;
  public static final int ADD = 33;
  public static final int NUMBER = 44;
  public static final int MOD = 40;
  public static final int MODULE = 2;
  public static final int RIGHTPAR = 25;
  public static final int COLON = 23;
  public static final int ELSE = 17;
  public static final int READ = 47;
  public static final int WHILE = 12;
  public static final int LEFTPAR = 24;
  public static final int THEN = 15;
  public static final int LEQ = 30;
  public static final int END = 4;
  public static final int VAR = 7;
  public static final int PROCEDURE = 8;
  public static final int DO = 13;
  public static final int IDENTIFIER = 43;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MODULE",
  "BEGIN",
  "END",
  "CONST",
  "TYPE",
  "VAR",
  "PROCEDURE",
  "RECORD",
  "ARRAY",
  "OF",
  "WHILE",
  "DO",
  "IF",
  "THEN",
  "ELSIF",
  "ELSE",
  "LEFTMIDPAR",
  "RIGHTMIDPAR",
  "SEMI",
  "DOT",
  "EQUAL",
  "COLON",
  "LEFTPAR",
  "RIGHTPAR",
  "COMMA",
  "COLONEQ",
  "NOTEQUAL",
  "LESS",
  "LEQ",
  "GREAT",
  "GEQ",
  "ADD",
  "UADD",
  "MINUS",
  "UMINUS",
  "OR",
  "MUL",
  "DIV",
  "MOD",
  "AND",
  "NOT",
  "IDENTIFIER",
  "NUMBER",
  "INT",
  "BOOL",
  "READ",
  "WRITE",
  "WRITELN"
  };
}

